services:

  mysql:
    image: mysql:8.0

    container_name: stugooo-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: stugooo
      MYSQL_USER: stugooo
      MYSQL_PASSWORD: StrongPassword
      MYSQL_ROOT_PASSWORD: RootPassword

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .

    container_name: stugooo-app

    restart: unless-stopped

    depends_on:
      - mysql

    volumes:
      - ./storage:/var/www/storage

  nginx:
    image: nginx:alpine

    container_name: stugooo-nginx

    restart: unless-stopped

    depends_on:
      - app

    ports:
      - "80:80"

    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_data:

